#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
#
# project.mk
#
# Shared internal project structure.
#
# Responsibilities:
#   - Derive internal paths (repo root, nvim src, build, stage, vendor).
#   - Bridge user-facing knobs from environment.mk into the variables expected
#     by other *.mk files (e.g., NVIM_ROCKS_DIR, LUAROCKS_CONFIG).
#   - Generate build/m4/config_env.m4 with content-comparison idempotence.
#   - Provide a summary block suitable for "make show".
#
# Assumptions:
#   - environment.mk has already been included and defines:
#       XDG_CONFIG_HOME, XDG_CACHE_HOME,
#       NVIM_CONFIG_DIR, NVIM_CACHE_DIR,
#       tool variables (NVIM, LUA, RSYNC, GIT, AWK, M4, ...)
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#

#------------------------------------------------------------------------------#
# Repository layout (internal, not meant to be overridden)
#------------------------------------------------------------------------------#

# Root of the repository (assumed to be where Make is invoked)
repo_root      := ${CURDIR}

# Neovim source tree within the repo
nvim_src_dir   := ${repo_root}/nvim

# Build assets (e.g., m4 macros, vendored tools, helper scripts)
build_dir      := ${repo_root}/build
build_bin      := ${build_dir}/bin
m4_dir         := ${build_dir}/m4
scripts_dir    := ${build_dir}/scripts

# Vendored seed plugins (git submodules)
vendor_dir     := ${repo_root}/vendor

# Stage root and staged Neovim tree (assembled image)
stage_dir      := ${repo_root}/stage
stage_nvim_dir := ${stage_dir}/nvim

#------------------------------------------------------------------------------#
# Hermetic rocks tree + bridge knobs
#------------------------------------------------------------------------------#

# Derive a cache root from NVIM_CACHE_DIR (user-facing knob from environment.mk).
nvim_cache_root     := ${NVIM_CACHE_DIR}

# Hermetic LuaRocks tree lives under ${nvim_rocks_dir}.
nvim_rocks_dir      := ${nvim_cache_root}/rocks
luarocks_config_dir := ${nvim_rocks_dir}/luarocks
luarocks_config     := ${luarocks_config_dir}/config.lua

# Stable aliases so other *.mk files don't need to re-derive paths.
NVIM_ROCKS_DIR      := ${nvim_rocks_dir}
LUAROCKS_CONFIG_DIR := ${luarocks_config_dir}
LUAROCKS_CONFIG     := ${luarocks_config}

#------------------------------------------------------------------------------#
# Stamp configuration into a file
#------------------------------------------------------------------------------#

config_env := ${m4_dir}/config_env.m4

# IMPORTANT DISCIPLINE (order-only dependency):
#   ${config_env} is intentionally PHONY so it is re-evaluated every run (env is
#   not a file; timestamps cannot represent env changes).
#
#   Any target that *requires* the existence of ${config_env} but should only
#   rebuild when its *contents* change MUST depend on it as an order-only prereq:
#
#     some_target: other_prereqs | ${config_env}
#
#   If you mistakenly use it as a normal prerequisite:
#
#     some_target: ${config_env}
#
#   then some_target will rebuild every run (because ${config_env} is PHONY).
#
.PHONY: ${config_env}
${config_env}:
	@mkdir -p "$(dir $@)"
	@set -eu; \
	  tmp="$$(mktemp "$(dir $@)/.config_env.m4.XXXXXX")"; \
	  { \
	    echo "m4_dnl Auto-generated by project.mk; do not edit"; \
	    echo "m4_define(\`NV_M4_NVIM_ROCKS_DIR', \`${nvim_rocks_dir}')"; \
	    echo "m4_define(\`NV_M4_LUAROCKS_CONFIG_DIR', \`${luarocks_config_dir}')"; \
	    echo "m4_define(\`NV_M4_LUAROCKS_CONFIG', \`${luarocks_config}')"; \
	  } > "$$tmp"; \
	  if [ ! -f "$@" ] || ! cmp -s "$$tmp" "$@"; then \
	    mv "$$tmp" "$@"; \
	  else \
	    rm -f "$$tmp"; \
	  fi

#------------------------------------------------------------------------------#
# Project summary (for "make show" or similar)
#------------------------------------------------------------------------------#

define project_summary
  Repository root............ ${repo_root}

  # Source / build layout
  Neovim source.............. ${nvim_src_dir}
  Build dir.................. ${build_dir}
  M4 template dir............ ${m4_dir}
  Vendor dir................. ${vendor_dir}
  Stage dir.................. ${stage_dir}
  Stage Neovim............... ${stage_nvim_dir}

  # Install / cache layout
  NVIM_CONFIG_DIR............ ${NVIM_CONFIG_DIR}
  NVIM_CACHE_DIR............. ${NVIM_CACHE_DIR}
  NVIM_ROCKS_DIR............. ${NVIM_ROCKS_DIR}
  LUAROCKS_CONFIG_DIR........ ${LUAROCKS_CONFIG_DIR}
  LUAROCKS_CONFIG............ ${LUAROCKS_CONFIG}
  config_env.m4.............. ${config_env}
endef

#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
