m4_dnl env.lua.m4
m4_dnl
m4_dnl Hermetic Neovim environment wiring.
m4_dnl Rendered at build time: env.lua.m4 → env.lua
m4_dnl
m4_dnl Includes constants.m4 and paths.m4 (both use default m4 quoting).
m4_dnl Macro references are placed outside quotes so they expand at render time.
m4_dnl
m4_dnl NOTE: This file does NOT include common.m4 (no backticks in the Lua body).
m4_dnl The default m4 quoting (backtick/single-quote) is fine here because Lua
m4_dnl strings use double quotes, and m4 does not treat " as special.
m4_dnl
m4_include(`constants.m4')m4_dnl
m4_include(`paths.m4')m4_dnl
-- config/env.lua (generated from env.lua.m4 — do not edit)
--
-- Wires Neovim to the hermetic rocks tree installed by luarocks.
-- All paths are stamped at build time via m4. No runtime probing.
--
-- Design (Option B — luarocks-first):
--   rocks.nvim and companions are installed as luarocks packages (not vendored).
--   This module wires package.path/cpath so their Lua modules load, and adds
--   the rocks.nvim runtime directory to rtp so plugin/rocks.lua is sourced
--   (which registers the :Rocks command, autocmds, etc.).

local M = {}

-- Build-time injected roots
M.nvim_rocks_dir      = "NV_M4_NVIM_ROCKS_DIR"
M.luarocks_config     = "NV_M4_LUAROCKS_CONFIG"
M.luarocks_config_dir = "NV_M4_LUAROCKS_CONFIG_DIR"

-- Luarocks wrapper: a single executable script (generated by seed.mk) that
-- invokes the host luarocks under the validated Lua 5.1 / LuaJIT binary
-- with hermetic LUAROCKS_CONFIG, LUA_PATH, and LUA_CPATH.
-- rocks.nvim calls this via vim.system() which requires a single path.
M.luarocks_wrapper = "NV_M4_LUAROCKS_WRAPPER"

-- rocks.nvim runtime path inside the luarocks tree
-- (contains plugin/rocks.lua which registers :Rocks commands)
M.rocks_rtp = "NV_M4_ROCKS_RTP"

-- Lua module directories under the hermetic rocks tree
M.lua_share_dir = "NV_M4_NVIM_ROCKS_DIR/share/lua/NV_M4_LUA_VER"
M.lua_lib_dir   = "NV_M4_NVIM_ROCKS_DIR/lib/lua/NV_M4_LUA_VER"

-- Prepend a semicolon-separated path string (Lua package path style)
local function prepend_path(original, prefix)
  if not original or original == "" then
    return prefix
  end
  return prefix .. ";" .. original
end

local function setup_paths()
  -- Allow requiring this module outside Neovim without error.
  if not vim then
    return
  end

  ---------------------------------------------------------------------------
  -- 1) Export LUAROCKS_CONFIG into the Neovim process environment.
  ---------------------------------------------------------------------------
  vim.env.LUAROCKS_CONFIG = M.luarocks_config

  ---------------------------------------------------------------------------
  -- 2) Export hermetic LUA_PATH / LUA_CPATH into the process environment.
  --
  --    Any subprocess spawned by rocks.nvim (e.g., luarocks queries to
  --    determine installed rocks) inherits these variables.  Without them,
  --    the subprocess may find modules from user-global trees like
  --    ~/.local/share/lua/5.1/ — which can contain luarocks code compiled
  --    for Lua 5.4 that fails under Lua 5.1 / LuaJIT.
  --
  --    No trailing ";;" — paths are exclusive to the hermetic tree.
  ---------------------------------------------------------------------------
  do
    local lua_path = table.concat({
      M.lua_share_dir .. "/?.lua",
      M.lua_share_dir .. "/?/init.lua",
    }, ";")
    vim.env.LUA_PATH = lua_path
  end

  do
    local lua_cpath = table.concat({
      M.lua_lib_dir .. "/?.so",
      M.lua_lib_dir .. "/?.dylib",
      M.lua_lib_dir .. "/?.dll",
    }, ";")
    vim.env.LUA_CPATH = lua_cpath
  end

  ---------------------------------------------------------------------------
  -- 3) Wire Lua module search paths to the hermetic rocks tree.
  --    This makes rocks.nvim dependencies (nio, toml-edit, etc.) loadable
  --    within this Neovim process.
  ---------------------------------------------------------------------------
  do
    local lua_paths = table.concat({
      M.lua_share_dir .. "/?.lua",
      M.lua_share_dir .. "/?/init.lua",
    }, ";")
    package.path = prepend_path(package.path, lua_paths)
  end

  do
    local c_paths = table.concat({
      M.lua_lib_dir .. "/?.so",
      M.lua_lib_dir .. "/?.dylib",
      M.lua_lib_dir .. "/?.dll",
    }, ";")
    package.cpath = prepend_path(package.cpath, c_paths)
  end

  ---------------------------------------------------------------------------
  -- 4) Add rocks.nvim runtime to rtp.
  --    This is the versioned directory inside the luarocks tree that contains
  --    plugin/rocks.lua (registers :Rocks command and sources runtime files).
  ---------------------------------------------------------------------------
  vim.opt.runtimepath:append(M.rocks_rtp)

  ---------------------------------------------------------------------------
  -- 5) Merge hermetic config into vim.g.rocks_nvim.
  --    Layer onto any existing table instead of clobbering it.
  --
  --    luarocks_binary: the wrapper script generated by seed.mk.  This is
  --    a single executable that rocks.nvim can pass to vim.system().  It
  --    invokes luarocks under the validated Lua 5.1 / LuaJIT interpreter
  --    with hermetic environment variables, avoiding the shebang problem
  --    where the luarocks binary inside the rocks tree would otherwise
  --    execute under the system Lua 5.4+ and fail with "attempt to assign
  --    to const variable".
  ---------------------------------------------------------------------------
  local existing = vim.g.rocks_nvim
  if type(existing) ~= "table" then
    existing = {}
  end

  vim.g.rocks_nvim = vim.tbl_extend("force", existing, {
    rocks_path      = M.nvim_rocks_dir,
    luarocks_binary = M.luarocks_wrapper,
  })
end

-- Public API
M.setup_paths = setup_paths
M.load = setup_paths

-- Requiring this module wires the hermetic paths immediately.
setup_paths()

return M
m4_dnl vim: ft=lua
